JE-22008

diff --git a/.openshift/action_hooks/stop b/.openshift/action_hooks/stop
--- a/.openshift/action_hooks/stop
+++ b/.openshift/action_hooks/stop
@@ -1,13 +1,12 @@
 #!/bin/bash
 
-# Ensure the previous startup succeeded and this actually exists.
-if [ -d "${OPENSHIFT_JETTY8_DIR}/versions/8.14" ]; then
-    cd ${OPENSHIFT_JETTY8_DIR}/versions/8.14/
+jetty_pid=`ps aux|grep java|grep jetty|grep -v grep|awk '{print $2}'`;
 
-    # Ensure the process is actually running.
-    if ps -p `cat jetty.pid` > /dev/null
+    if [ -n "$jetty_pid" ] 
     then
-       kill `cat jetty.pid` && echo "Jetty8 stopped successfully"
+       kill $jetty_pid && echo "Jetty8 stopped successfully" || echo "Jetty8 stop failed"
+    else 
+	echo "Jetty8 already stopped";
     fi
-fi
+
 
